image: "ruby:2.5"

services:
  - postgres:alpine

variables:
  POSTGRES_USER: test
  POSTGRES_PASSSWORD: test-password
  POSTGRES_DB: test_db
  DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSSWORD}@postgres/${POSTGRES_DB}
  RAILS_ENV: test

before_script:
  - apt-get update -qq && apt-get install -yqq nodejs libpq-dev
  - gem install bundler  --no-ri --no-rdoc
  - gem install rake -v 12.0.0 --no-ri --no-rdoc
  - bundle install --path vendor
  - rails db:migrate
  - rails db:seed

rails:
  script:
    - rails test

rubocop:
  script:
    - rubocop