image: "ruby:2.5"

services:
  - postgres:alpine

stages:
  - test
  - deploy

test_all:
  stage: test
  variables:
    POSTGRES_USER: test
    POSTGRES_PASSSWORD: test-password
    POSTGRES_DB: test_db
    DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSSWORD}@postgres/${POSTGRES_DB}
    RAILS_ENV: test

  before_script:
    - apt-get update -qq && apt-get install -yqq nodejs libpq-dev
    - gem install bundler  --no-ri --no-rdoc
    - bundle install
    - rails db:migrate
    - rails db:seed

  script:
    - rubocop
    - rails test

production_deploys:
  stage: deploy
  variables:
    RAILS_ENV: production
  only:
    - master
  script:
    - ssh -t ubuntu@34.202.235.10 "cd social_linking && git pull && rake db:migrate && rake asset:precompile && touch tmp/restart.txt && sudo service apache2 restart"
