inherit_gem:
  rubocop-rails:
    - config/rails.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/*'
    - 'Gemfile'
    - 'config/boot.rb'
    - 'vendor/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false
